### ISSUE TITLE
Tag for dxfile?

### ISSUE THREAD

**Issue by ericdill** [data-exchange/dxfile#6]
I'm in the process of writing a recipe for tomopy (cc @dgursoy @licode ) to add it and its dependencies to conda-forge at conda-forge/staged-recipes#681 and need to package this as part of that process. Would it be possible to get a tag on this project so I can point at a tag instead of a git hash?

Thanks!

**Comment by decarlof** [comment]
done, please use @decarlof as maintainer

**Comment by ericdill** [comment]
Will do. Thanks!
